/**
 * Maps eloratings.net 2-letter codes to our FIFA 3-letter PocketBase team codes.
 * @see https://www.eloratings.net/World.tsv (columns: rank, rank, code, elo, …)
 */
export const ELO_CODE_TO_TEAM: Record<string, string> = {
  ES: "ESP",
  AR: "ARG",
  FR: "FRA",
  EN: "ENG",
  BR: "BRA",
  PT: "POR",
  CO: "COL",
  NL: "NED",
  EC: "ECU",
  DE: "GER",
  NO: "NOR",
  HR: "CRO",
  TR: "TUR",
  JP: "JPN",
  BE: "BEL",
  UY: "URU",
  CH: "SUI",
  MX: "MEX",
  SN: "SEN",
  PY: "PAR",
  AT: "AUT",
  MA: "MAR",
  CA: "CAN",
  SQ: "SCO",
  AU: "AUS",
  IR: "IRN",
  DZ: "ALG",
  KR: "KOR",
  CZ: "CZE",
  PA: "PAN",
  US: "USA",
  UZ: "UZB",
  SE: "SWE",
  EG: "EGY",
  CI: "CIV",
  JO: "JOR",
  CD: "COD",
  IQ: "IRQ",
  BA: "BIH",
  CV: "CPV",
  SA: "KSA",
  NZ: "NZL",
  HT: "HAI",
  GH: "GHA",
  ZA: "RSA",
  CW: "CUW",
  QA: "QAT",
  TN: "TUN",
};
